repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  - id: check-added-large-files
  - id: check-byte-order-marker
  - id: check-case-conflict
  - id: check-merge-conflict
  - id: detect-private-key
  - id: end-of-file-fixer
  - id: file-contents-sorter
    args:
    - --unique
    files: ^.gitignore|.dict
  - id: fix-byte-order-marker
  - id: forbid-new-submodules
  - id: forbid-submodules
  - id: mixed-line-ending
    args:
    - --fix=lf
  - id: trailing-whitespace
  # SHELL
  - id: check-executables-have-shebangs
  - id: check-shebang-scripts-are-executable
  - id: check-symlinks
  - id: destroyed-symlinks
  # PYTHON
  - id: check-builtin-literals
  - id: check-docstring-first
  - id: debug-statements
  - id: fix-encoding-pragma
  - id: requirements-txt-fixer
  # JSON
  - id: check-json
  - id: pretty-format-json
    args:
    - --autofix
    - --indent
    - '4'
  # TOML
  - id: check-toml
  # XML
  - id: check-xml
  # YAML
  - id: check-yaml
# YAML
- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.11.0
  hooks:
  - id: pretty-format-yaml
    args:
    - --autofix
    - --indent
    - '2'
- repo: https://github.com/adrienverge/yamllint
  rev: v1.32.0
  hooks:
  - id: yamllint
# MARKDOWN
- repo: https://github.com/executablebooks/mdformat
  rev: 0.7.17
  hooks:
  - id: mdformat
    args:
    - --end-of-line
    - lf
    additional_dependencies:
    - mdformat-gfm
    - mdformat-black
- repo: https://github.com/igorshubovych/markdownlint-cli
  rev: v0.37.0
  hooks:
  - id: markdownlint
# PYTHON
- repo: https://github.com/psf/black
  rev: 23.10.0
  hooks:
  - id: black
    language_version: python3
- repo: https://github.com/pycqa/isort
  rev: 5.12.0
  hooks:
  - id: isort
    args:
    - --profile
    - black
    - --filter-files
    - --force-single-line-imports
- repo: https://github.com/pycqa/flake8
  rev: 6.1.0
  hooks:
  - id: flake8
    args:
    - --extend-ignore=E203
    - --max-line-length=88
- repo: https://github.com/PyCQA/pylint
  rev: v3.0.1
  hooks:
  - id: pylint
# SHELL
- repo: https://github.com/lovesegfault/beautysh
  rev: v6.2.1
  hooks:
  - id: beautysh
    types: [bash, shell]
    args:
    - --indent-size
    - '4'
- repo: https://github.com/shellcheck-py/shellcheck-py
  rev: v0.9.0.6
  hooks:
  - id: shellcheck
# Spell Checker
- repo: https://github.com/streetsidesoftware/cspell-cli
  rev: v7.3.2
  hooks:
  - id: cspell
    exclude: ^.gitignore|^.pre-commit-config.yaml|^.cspell
